### ISSUE TITLE
Bug: Duplicate Campaign Contacts

### ISSUE THREAD

**Issue by the-alex** [hrnyc-targaryen/thesis#85]
Don't allow the user to submit the same email twice to a campaign. Even though this doesn't cause an error with SendGrid, displaying duplicate campaign contacts _looks_ like a bug, and we should prevent the user from doing it.

**Comment by Defection** [comment]
Note: Some data isnt being passed around correctly. Newly added contacts on delete after a page refresh. Cockaroach
